// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ask/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ask">> = Specific
  const handler = {} as typeof import("../../app/ask/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookmarks">> = Specific
  const handler = {} as typeof import("../../app/bookmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/campus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campus">> = Specific
  const handler = {} as typeof import("../../app/campus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/careers/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers/[slug]">> = Specific
  const handler = {} as typeof import("../../app/careers/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/discover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/discover">> = Specific
  const handler = {} as typeof import("../../app/discover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/questions/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questions/[slug]">> = Specific
  const handler = {} as typeof import("../../app/questions/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/admin/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/answers/[id]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/answers/[id]/accept">> = Specific
  const handler = {} as typeof import("../../app/api/answers/[id]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/answers/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/answers/[id]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/answers/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/answers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/answers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/answers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/answers/[id]/upvote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/answers/[id]/upvote">> = Specific
  const handler = {} as typeof import("../../app/api/answers/[id]/upvote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campus/events/[id]/rsvp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campus/events/[id]/rsvp">> = Specific
  const handler = {} as typeof import("../../app/api/campus/events/[id]/rsvp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campus/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campus/events">> = Specific
  const handler = {} as typeof import("../../app/api/campus/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campus/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campus/requests">> = Specific
  const handler = {} as typeof import("../../app/api/campus/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/careers/companies/[id]/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/careers/companies/[id]/reviews">> = Specific
  const handler = {} as typeof import("../../app/api/careers/companies/[id]/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/careers/opportunities/[id]/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/careers/opportunities/[id]/save">> = Specific
  const handler = {} as typeof import("../../app/api/careers/opportunities/[id]/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/careers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/careers">> = Specific
  const handler = {} as typeof import("../../app/api/careers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/comments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/comments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]/read">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/questions/[id]/answers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questions/[id]/answers">> = Specific
  const handler = {} as typeof import("../../app/api/questions/[id]/answers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/questions/[id]/bookmark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questions/[id]/bookmark">> = Specific
  const handler = {} as typeof import("../../app/api/questions/[id]/bookmark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/questions/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questions/[id]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/questions/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/questions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questions/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/questions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/questions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/questions">> = Specific
  const handler = {} as typeof import("../../app/api/questions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/realtime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime">> = Specific
  const handler = {} as typeof import("../../app/api/realtime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/topics/[id]/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/topics/[id]/follow">> = Specific
  const handler = {} as typeof import("../../app/api/topics/[id]/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/topics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/topics">> = Specific
  const handler = {} as typeof import("../../app/api/topics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/[id]/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/follow">> = Specific
  const handler = {} as typeof import("../../app/api/users/[id]/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/me">> = Specific
  const handler = {} as typeof import("../../app/api/users/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
