// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/ask" | "/bookmarks" | "/campus" | "/careers" | "/careers/[slug]" | "/colleges" | "/colleges/[slug]" | "/community" | "/discover" | "/forgot-password" | "/login" | "/notifications" | "/questions/[slug]" | "/register" | "/reset-password" | "/settings/profile" | "/students" | "/u/[username]"
type AppRouteHandlerRoutes = "/api/admin/analytics" | "/api/admin/reports" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/answers/[id]" | "/api/answers/[id]/accept" | "/api/answers/[id]/comments" | "/api/answers/[id]/upvote" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/auth/reset-password" | "/api/campus/events" | "/api/campus/events/[id]/rsvp" | "/api/campus/requests" | "/api/careers" | "/api/careers/companies/[id]/reviews" | "/api/careers/opportunities/[id]/save" | "/api/colleges" | "/api/colleges/[id]" | "/api/colleges/[id]/issues" | "/api/colleges/[id]/join" | "/api/colleges/[id]/markets" | "/api/comments/[id]" | "/api/institutions" | "/api/issues/[id]" | "/api/issues/[id]/vote" | "/api/markets/[id]/produce" | "/api/notifications" | "/api/notifications/[id]/read" | "/api/questions" | "/api/questions/[id]" | "/api/questions/[id]/answers" | "/api/questions/[id]/bookmark" | "/api/questions/[id]/comments" | "/api/questions/[id]/like" | "/api/realtime" | "/api/reports" | "/api/search" | "/api/students" | "/api/topics" | "/api/topics/[id]/follow" | "/api/users" | "/api/users/[id]/follow" | "/api/users/me"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/admin/analytics": {}
  "/api/admin/reports": {}
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/answers/[id]": { "id": string; }
  "/api/answers/[id]/accept": { "id": string; }
  "/api/answers/[id]/comments": { "id": string; }
  "/api/answers/[id]/upvote": { "id": string; }
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/campus/events": {}
  "/api/campus/events/[id]/rsvp": { "id": string; }
  "/api/campus/requests": {}
  "/api/careers": {}
  "/api/careers/companies/[id]/reviews": { "id": string; }
  "/api/careers/opportunities/[id]/save": { "id": string; }
  "/api/colleges": {}
  "/api/colleges/[id]": { "id": string; }
  "/api/colleges/[id]/issues": { "id": string; }
  "/api/colleges/[id]/join": { "id": string; }
  "/api/colleges/[id]/markets": { "id": string; }
  "/api/comments/[id]": { "id": string; }
  "/api/institutions": {}
  "/api/issues/[id]": { "id": string; }
  "/api/issues/[id]/vote": { "id": string; }
  "/api/markets/[id]/produce": { "id": string; }
  "/api/notifications": {}
  "/api/notifications/[id]/read": { "id": string; }
  "/api/questions": {}
  "/api/questions/[id]": { "id": string; }
  "/api/questions/[id]/answers": { "id": string; }
  "/api/questions/[id]/bookmark": { "id": string; }
  "/api/questions/[id]/comments": { "id": string; }
  "/api/questions/[id]/like": { "id": string; }
  "/api/realtime": {}
  "/api/reports": {}
  "/api/search": {}
  "/api/students": {}
  "/api/topics": {}
  "/api/topics/[id]/follow": { "id": string; }
  "/api/users": {}
  "/api/users/[id]/follow": { "id": string; }
  "/api/users/me": {}
  "/ask": {}
  "/bookmarks": {}
  "/campus": {}
  "/careers": {}
  "/careers/[slug]": { "slug": string; }
  "/colleges": {}
  "/colleges/[slug]": { "slug": string; }
  "/community": {}
  "/discover": {}
  "/forgot-password": {}
  "/login": {}
  "/notifications": {}
  "/questions/[slug]": { "slug": string; }
  "/register": {}
  "/reset-password": {}
  "/settings/profile": {}
  "/students": {}
  "/u/[username]": { "username": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
